<?php

// The 200 most common English words, and quotes from public-domain works.
return [
    'words' => [
        'the', 'be', 'of', 'and', 'a', 'to', 'in', 'he', 'have', 'it',
        'that', 'for', 'they', 'i', 'with', 'as', 'not', 'on', 'she', 'at',
        'by', 'this', 'we', 'you', 'do', 'but', 'from', 'or', 'which', 'one',
        'would', 'all', 'will', 'there', 'say', 'who', 'make', 'when', 'can', 'more',
        'if', 'no', 'man', 'out', 'other', 'so', 'what', 'time', 'up', 'go',
        'about', 'than', 'into', 'could', 'state', 'only', 'new', 'year', 'some', 'take',
        'come', 'these', 'know', 'see', 'use', 'get', 'like', 'then', 'first', 'any',
        'work', 'now', 'may', 'such', 'give', 'over', 'think', 'most', 'even', 'find',
        'day', 'also', 'after', 'way', 'many', 'must', 'look', 'before', 'great', 'back',
        'through', 'long', 'where', 'much', 'should', 'well', 'people', 'down', 'own', 'just',
        'because', 'good', 'each', 'those', 'feel', 'seem', 'how', 'high', 'too', 'place',
        'little', 'world', 'very', 'still', 'nation', 'hand', 'old', 'life', 'tell', 'write',
        'become', 'here', 'show', 'house', 'both', 'between', 'need', 'mean', 'call', 'develop',
        'under', 'last', 'right', 'move', 'thing', 'general', 'school', 'never', 'same', 'another',
        'begin', 'while', 'number', 'part', 'turn', 'real', 'leave', 'might', 'want', 'point',
        'form', 'off', 'child', 'few', 'small', 'since', 'against', 'ask', 'late', 'home',
        'interest', 'large', 'person', 'end', 'open', 'public', 'follow', 'during', 'present', 'without',
        'again', 'hold', 'govern', 'around', 'possible', 'head', 'consider', 'word', 'program', 'problem',
        'however', 'lead', 'system', 'set', 'order', 'eye', 'plan', 'run', 'keep', 'face',
        'fact', 'group', 'play', 'stand', 'increase', 'early', 'course', 'change', 'help', 'line',
    ],
    'quotes' => [
        ['text' => 'It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife.', 'source' => 'Jane Austen, Pride and Prejudice'],
        ['text' => 'I declare after all there is no enjoyment like reading! How much sooner one tires of any thing than of a book!', 'source' => 'Jane Austen, Pride and Prejudice'],
        ['text' => 'It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness.', 'source' => 'Charles Dickens, A Tale of Two Cities'],
        ['text' => 'It is a far, far better thing that I do, than I have ever done; it is a far, far better rest that I go to than I have ever known.', 'source' => 'Charles Dickens, A Tale of Two Cities'],
        ['text' => 'Marley was dead: to begin with. There is no doubt whatever about that.', 'source' => 'Charles Dickens, A Christmas Carol'],
        ['text' => 'Call me Ishmael. Some years ago, never mind how long precisely, having little or no money in my purse, and nothing particular to interest me on shore, I thought I would sail about a little and see the watery part of the world.', 'source' => 'Herman Melville, Moby-Dick'],
        ['text' => 'Happy families are all alike; every unhappy family is unhappy in its own way.', 'source' => 'Leo Tolstoy, Anna Karenina'],
        ['text' => 'We are all in the gutter, but some of us are looking at the stars.', 'source' => "Oscar Wilde, Lady Windermere's Fan"],
        ['text' => 'The only way to get rid of a temptation is to yield to it.', 'source' => 'Oscar Wilde, The Picture of Dorian Gray'],
        ['text' => 'To live is the rarest thing in the world. Most people exist, that is all.', 'source' => 'Oscar Wilde, The Soul of Man under Socialism'],
        ['text' => 'Work consists of whatever a body is obliged to do, and Play consists of whatever a body is not obliged to do.', 'source' => 'Mark Twain, The Adventures of Tom Sawyer'],
        ['text' => "All right, then, I'll go to hell.", 'source' => 'Mark Twain, Adventures of Huckleberry Finn'],
        ['text' => 'Few things are harder to put up with than the annoyance of a good example.', 'source' => "Mark Twain, Pudd'nhead Wilson"],
        ['text' => "All the world's a stage, and all the men and women merely players; they have their exits and their entrances.", 'source' => 'William Shakespeare, As You Like It'],
        ['text' => 'To be, or not to be, that is the question.', 'source' => 'William Shakespeare, Hamlet'],
        ['text' => 'The fault, dear Brutus, is not in our stars, but in ourselves, that we are underlings.', 'source' => 'William Shakespeare, Julius Caesar'],
        ['text' => 'We are such stuff as dreams are made on, and our little life is rounded with a sleep.', 'source' => 'William Shakespeare, The Tempest'],
        ['text' => "Why, sometimes I've believed as many as six impossible things before breakfast.", 'source' => 'Lewis Carroll, Through the Looking-Glass'],
        ['text' => 'Begin at the beginning, and go on till you come to the end: then stop.', 'source' => "Lewis Carroll, Alice's Adventures in Wonderland"],
        ['text' => 'So we beat on, boats against the current, borne back ceaselessly into the past.', 'source' => 'F. Scott Fitzgerald, The Great Gatsby'],
        ['text' => 'I am no bird; and no net ensnares me: I am a free human being with an independent will.', 'source' => 'Charlotte Bronte, Jane Eyre'],
        ['text' => 'I went to the woods because I wished to live deliberately, to front only the essential facts of life.', 'source' => 'Henry David Thoreau, Walden'],
        ['text' => 'The mass of men lead lives of quiet desperation.', 'source' => 'Henry David Thoreau, Walden'],
        ['text' => 'A foolish consistency is the hobgoblin of little minds.', 'source' => 'Ralph Waldo Emerson, Self-Reliance'],
        ['text' => 'When you have eliminated the impossible, whatever remains, however improbable, must be the truth.', 'source' => 'Arthur Conan Doyle, The Sign of the Four'],
        ['text' => 'You see, but you do not observe. The distinction is clear.', 'source' => 'Arthur Conan Doyle, A Scandal in Bohemia'],
        ['text' => 'The Time Traveller (for so it will be convenient to speak of him) was expounding a recondite matter to us.', 'source' => 'H. G. Wells, The Time Machine'],
        ['text' => 'Four score and seven years ago our fathers brought forth on this continent, a new nation, conceived in Liberty, and dedicated to the proposition that all men are created equal.', 'source' => 'Abraham Lincoln, Gettysburg Address'],
        ['text' => 'All that we see or seem is but a dream within a dream.', 'source' => 'Edgar Allan Poe, A Dream Within a Dream'],
        ['text' => 'Two roads diverged in a wood, and I, I took the one less traveled by, and that has made all the difference.', 'source' => 'Robert Frost, The Road Not Taken'],
        ['text' => 'Hope is the thing with feathers that perches in the soul, and sings the tune without the words, and never stops at all.', 'source' => 'Emily Dickinson'],
        ['text' => 'I celebrate myself, and sing myself, and what I assume you shall assume.', 'source' => 'Walt Whitman, Song of Myself'],
        ['text' => 'Beware; for I am fearless, and therefore powerful.', 'source' => 'Mary Shelley, Frankenstein'],
    ],
];
