<?php

// 200 mots courants du français, et des citations d'oeuvres du domaine public.
return [
    'words' => [
        'le', 'la', 'les', 'de', 'des', 'du', 'un', 'une', 'et', 'à',
        'en', 'au', 'aux', 'il', 'elle', 'ils', 'elles', 'on', 'je', 'tu',
        'nous', 'vous', 'me', 'te', 'se', 'lui', 'leur', 'son', 'sa', 'ses',
        'mon', 'ma', 'mes', 'ton', 'ta', 'tes', 'notre', 'votre', 'ce', 'cette',
        'ces', 'qui', 'que', 'quoi', 'dont', 'où', 'ne', 'pas', 'plus', 'rien',
        'jamais', 'toujours', 'encore', 'déjà', 'aussi', 'très', 'bien', 'mal', 'peu', 'beaucoup',
        'trop', 'tout', 'tous', 'toute', 'toutes', 'avec', 'sans', 'pour', 'par', 'sur',
        'sous', 'dans', 'chez', 'vers', 'entre', 'avant', 'après', 'depuis', 'pendant', 'contre',
        'comme', 'mais', 'ou', 'donc', 'car', 'si', 'quand', 'alors', 'puis', 'est',
        'sont', 'était', 'être', 'avoir', 'a', 'ont', 'avait', 'fait', 'faire', 'dit',
        'dire', 'peut', 'pouvoir', 'veut', 'vouloir', 'va', 'aller', 'vient', 'venir', 'voir',
        'sait', 'savoir', 'prendre', 'mettre', 'donner', 'trouver', 'parler', 'penser', 'passer', 'rester',
        'croire', 'aimer', 'jour', 'nuit', 'temps', 'année', 'fois', 'heure', 'moment', 'vie',
        'monde', 'homme', 'femme', 'enfant', 'père', 'mère', 'fils', 'fille', 'ami', 'main',
        'tête', 'yeux', 'voix', 'porte', 'maison', 'ville', 'pays', 'terre', 'eau', 'mer',
        'ciel', 'air', 'feu', 'soleil', 'route', 'chose', 'mot', 'nom', 'idée', 'place',
        'côté', 'fin', 'début', 'part', 'question', 'travail', 'argent', 'livre', 'table', 'chambre',
        'école', 'grand', 'petit', 'bon', 'nouveau', 'vieux', 'jeune', 'beau', 'premier', 'dernier',
        'autre', 'même', 'seul', 'long', 'haut', 'deux', 'trois', 'quatre', 'cinq', 'dix',
        'cent', 'mille', 'ici', 'là', 'non', 'oui', 'assez', 'moins', 'demain', 'hier',
    ],
    'quotes' => [
        ['text' => 'Rien ne sert de courir; il faut partir à point.', 'source' => 'Jean de La Fontaine, Le Lièvre et la Tortue'],
        ['text' => 'La raison du plus fort est toujours la meilleure.', 'source' => "Jean de La Fontaine, Le Loup et l'Agneau"],
        ['text' => "On a souvent besoin d'un plus petit que soi.", 'source' => 'Jean de La Fontaine, Le Lion et le Rat'],
        ['text' => "Apprenez que tout flatteur vit aux dépens de celui qui l'écoute.", 'source' => 'Jean de La Fontaine, Le Corbeau et le Renard'],
        ['text' => 'Patience et longueur de temps font plus que force ni que rage.', 'source' => 'Jean de La Fontaine, Le Lion et le Rat'],
        ['text' => 'Le bon sens est la chose du monde la mieux partagée.', 'source' => 'René Descartes, Discours de la méthode'],
        ['text' => 'Le coeur a ses raisons que la raison ne connaît point.', 'source' => 'Blaise Pascal, Pensées'],
        ['text' => "L'homme n'est qu'un roseau, le plus faible de la nature; mais c'est un roseau pensant.", 'source' => 'Blaise Pascal, Pensées'],
        ['text' => 'Cela est bien dit, mais il faut cultiver notre jardin.', 'source' => 'Voltaire, Candide'],
        ['text' => 'Il faut manger pour vivre, et non pas vivre pour manger.', 'source' => "Molière, L'Avare"],
        ['text' => "Aux âmes bien nées, la valeur n'attend point le nombre des années.", 'source' => 'Pierre Corneille, Le Cid'],
        ['text' => "Ce que l'on conçoit bien s'énonce clairement, et les mots pour le dire arrivent aisément.", 'source' => "Nicolas Boileau, L'Art poétique"],
        ['text' => 'Vingt fois sur le métier remettez votre ouvrage.', 'source' => "Nicolas Boileau, L'Art poétique"],
        ['text' => "Demain, dès l'aube, à l'heure où blanchit la campagne, je partirai. Vois-tu, je sais que tu m'attends.", 'source' => 'Victor Hugo, Les Contemplations'],
        ['text' => "Il dort. Quoique le sort fût pour lui bien étrange, il vivait. Il mourut quand il n'eut plus son ange.", 'source' => 'Victor Hugo, Les Misérables'],
        ['text' => 'Homme libre, toujours tu chériras la mer.', 'source' => "Charles Baudelaire, L'Homme et la mer"],
        ['text' => "Là, tout n'est qu'ordre et beauté, luxe, calme et volupté.", 'source' => "Charles Baudelaire, L'Invitation au voyage"],
        ['text' => 'Il pleure dans mon coeur comme il pleut sur la ville.', 'source' => 'Paul Verlaine, Romances sans paroles'],
        ['text' => "Les sanglots longs des violons de l'automne blessent mon coeur d'une langueur monotone.", 'source' => "Paul Verlaine, Chanson d'automne"],
        ['text' => 'Sous le pont Mirabeau coule la Seine et nos amours.', 'source' => 'Guillaume Apollinaire, Le Pont Mirabeau'],
        ['text' => "Vienne la nuit sonne l'heure, les jours s'en vont je demeure.", 'source' => 'Guillaume Apollinaire, Le Pont Mirabeau'],
        ['text' => "L'homme est né libre, et partout il est dans les fers.", 'source' => 'Jean-Jacques Rousseau, Du contrat social'],
        ['text' => "Parce que c'était lui, parce que c'était moi.", 'source' => 'Michel de Montaigne, Essais'],
        ['text' => "Chaque homme porte la forme entière de l'humaine condition.", 'source' => 'Michel de Montaigne, Essais'],
        ['text' => 'Tous pour un, un pour tous.', 'source' => 'Alexandre Dumas, Les Trois Mousquetaires'],
        ['text' => "Toute l'humaine sagesse sera dans ces deux mots: attendre et espérer.", 'source' => 'Alexandre Dumas, Le Comte de Monte-Cristo'],
        ['text' => 'La mer est tout. Elle couvre les sept dixièmes du globe terrestre.', 'source' => 'Jules Verne, Vingt mille lieues sous les mers'],
        ['text' => "La vie, voyez-vous, ça n'est jamais si bon ni si mauvais qu'on croit.", 'source' => 'Guy de Maupassant, Une vie'],
        ['text' => "La vérité est en marche et rien ne l'arrêtera.", 'source' => "Émile Zola, J'accuse"],
        ['text' => 'Un roman est un miroir qui se promène sur une grande route.', 'source' => 'Stendhal, Le Rouge et le Noir'],
        ['text' => 'Un seul être vous manque, et tout est dépeuplé.', 'source' => "Alphonse de Lamartine, L'Isolement"],
        ['text' => "Nous avons tous assez de force pour supporter les maux d'autrui.", 'source' => 'François de La Rochefoucauld, Maximes'],
        ['text' => "Je suis le ténébreux, le veuf, l'inconsolé, le prince d'Aquitaine à la tour abolie.", 'source' => 'Gérard de Nerval, El Desdichado'],
        ['text' => "Vivez, si m'en croyez, n'attendez à demain: cueillez dès aujourd'hui les roses de la vie.", 'source' => 'Pierre de Ronsard, Sonnets pour Hélène'],
        ['text' => 'Heureux qui, comme Ulysse, a fait un beau voyage.', 'source' => 'Joachim du Bellay, Les Regrets'],
        ['text' => 'Longtemps, je me suis couché de bonne heure.', 'source' => 'Marcel Proust, Du côté de chez Swann'],
    ],
];
